#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	SHIP,
	TARGET,
	PLAYER,
	FISH,
	BULLET,
	FLOOR,
	PLANE,
	TILE_PLATFORM,
	TILE_HAZARD,
	TILE_DECORATION,
	TILE_DOOR,
	EMPTY,
	BACKGROUND1,
	BACKGROUND2,
	BACKGROUND3,
	STORYBACKGROUND,
	START_BUTTON,
	RESUME_BUTTON,
	STORY_BUTTON,
	SETTINGS_BUTTON,
	RESTART_BUTTON,
	EXIT_BUTTON,
	BACK_BUTTON,
	NEXT_BUTTON,
	NUM_OF_TYPES
};
#endif /* defined (__GAME_OBJECT_TYPE__) */