#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_JUMP_UP_RIGHT,
	PLAYER_FALL_RIGHT,
	PLAYER_JUMP_UP_LEFT,
	PLAYER_FALL_LEFT,
	PLAYER_SWIM_RIGHT,
	PLAYER_SWIM_LEFT,
	PLAYER_DEATH_RIGHT,
	PLAYER_DEATH_LEFT,
	PLAYER_AB_IDLE_RIGHT,
	PLAYER_AB_IDLE_LEFT,
	PLAYER_AB_RUN_RIGHT,
	PLAYER_AB_RUN_LEFT,
	PLAYER_AB_JUMP_UP_RIGHT,
	PLAYER_AB_FALL_RIGHT,
	PLAYER_AB_JUMP_UP_LEFT,
	PLAYER_AB_FALL_LEFT,
	PLAYER_AB_SWIM_RIGHT,
	PLAYER_AB_SWIM_LEFT,
	PLAYER_AB_DEATH_RIGHT,
	PLAYER_AB_DEATH_LEFT,
	PLAYER_ICE_WALK_LEFT,
	PLAYER_ICE_IDLE_LEFT,
	PLAYER_ICE_JUMP_LEFT,
	PLAYER_ICE_FALL_LEFT,
	PLAYER_HURT_LEFT,
	PLAYER_ICE_WALK_RIGHT,
	PLAYER_ICE_IDLE_RIGHT,
	PLAYER_ICE_JUMP_RIGHT,
	PLAYER_ICE_FALL_RIGHT,
	PLAYER_ICE_ATK_LEFT,
	PLAYER_ICE_ATK_RIGHT,
	PLAYER_HURT_RIGHT,
	NUM_OF_ANIMATION_STATES
};
#endif /* defined (__PLAYER_ANIMATION_STATE__)*/