#pragma once
#ifndef __ENEMY_ANIMATION_STATE__
#define __ENEMY_ANIMATION_STATE__

enum EnemyAnimationState
{
	ENEMY_IDLE_RIGHT,
	ENEMY_IDLE_LEFT,
	ENEMY_ICE_IDLE_RIGHT,
	ENEMY_ICE_IDLE_LEFT,
	ENEMY_AB_IDLE_RIGHT,
	ENEMY_AB_IDLE_LEFT,
	ENEMY_RUN_RIGHT,
	ENEMY_RUN_LEFT,
	ENEMY_ICE_RUN_RIGHT,
	ENEMY_ICE_RUN_LEFT,
	ENEMY_AB_RUN_RIGHT,
	ENEMY_AB_RUN_LEFT,
	ENEMY_JUMP_UP_RIGHT,
	ENEMY_FALL_RIGHT,
	ENEMY_JUMP_UP_LEFT,
	ENEMY_FALL_LEFT,
	ENEMY_SWIM_RIGHT,
	ENEMY_SWIM_LEFT,
	ENEMY_DEATH_RIGHT,
	ENEMY_DEATH_LEFT,
	NUM_OF_ANIMATION_STATES_E
};

#endif /* defined (__ENEMY_ANIMATION_STATE__)*/