//For Future Use - Vashj

#pragma once
#ifndef __GREGORY_ANIMATION_STATE__
#define __GREGORY_ANIMATION_STATE__

enum GregoryAnimationState
{
	GREGORY_IDLE_RIGHT,
	GREGORY_IDLE_LEFT,
	GREGORY_RUN_RIGHT,
	GREGORY_RUN_LEFT,
	GREGORY_JUMP_UP_RIGHT,
	GREGORY_FALL_RIGHT,
	GREGORY_JUMP_UP_LEFT,
	GREGORY_FALL_LEFT,
	GREGORY_DEATH_RIGHT,
	GREGORY_DEATH_LEFT,
	GREGORY_HIT_LEFT,
	GREGORY_HIT_RIGHT,
	NUM_OF_ANIMATION_STATES_G
};

#endif /* defined (__GREGORY_ANIMATION_STATE__)*/